name: Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

      - run: |
          echo "Prev version ${{ steps.check_version.prev_version }}"
          echo "Version ${{ steps.check_version.version }}"
          echo "Version has changed ${{ steps.check_version.changed }}"
  
      - name: Execute if version has changed
        if: ${{ steps.check_version.outputs.changed }}
        run: echo "Version has changed from ${{ steps.check_version.outputs.prev_version }} to ${{ steps.check_version.outputs.version }}"

      - name: Tests
        run: |
          prev_version=$( echo "${{ steps.check_version.prev_version }}" )
          version=$( echo "${{ steps.check_version.version }}" )
          changed=$( echo "${{ steps.check_version.changed }}" )
          
          echo "Prev version ${prev_version}"
          echo "Version ${version}"
          echo "Version has changed ${changed}"

          if [[ "${ version }" != "0.42.0" ]]; then
            echo "Invalid `version`"
            exit 1
          fi
          if [[ "${ changed }" != true ]]; then
            echo "Invalid `changed`"
            exit 1
          fi
