name: Tests
on:
  push:
    branches: [ main ]

jobs:
  since_commit:
    name: Get since commit
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.since_commit.outputs.value }}
      
    steps:
      - name: Get since commit
        id: since_commit
        run: |
          since_commit=$( curl -X GET -u ${{ secrets.KVDB_SECRET }}: https://kvdb.io/${{ secrets.KVDB_BUCKET_ID }}/since_commit )
          since_commit=${since_commit:l}
          since_commit=${since_commit%%\%}
          if [[ $since_commit == not\ found* ]]; then
            since_commit=""
          echo "since commit $since_commit"
          echo "value=$since_commit" >> "$GITHUB_OUTPUT"

  check_version:
    name: Check version
    needs: [since_commit]
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_version.outputs.changed }}
      version: ${{ steps.check_version.outputs.version }}
      prev_version: ${{ steps.check_version.outputs.prev_version }}
      
    steps:
      - uses: actions/checkout@v4

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main
        with:
          since_commit: ${{ needs.since_commit.outputs.value }}

      - name: Save since commit
        run: |
          last_commit=$( git rev-parse HEAD )
          echo "last_commit $last_commit"
          curl -X POST -u ${{ secrets.KVDB_SECRET }}: https://kvdb.io/${{ secrets.KVDB_BUCKET_ID }}/since_commit -d $last_commit

  conditional_job:
    name: Conditonal job
    needs: [check_version]
    if: ${{ needs.check_version.outputs.changed }}
    runs-on: ubuntu-latest

    steps:
      - run: touch 42
      
      - name: Upload a file to mark that job executed
        uses: actions/upload-artifact@v4
        with:
          name: 42
          path: ./42
            
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for conditional job
        run: sleep 60

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

      - name: Test check_version step
        run: |
          prev_version=${{ steps.check_version.outputs.prev_version }}
          version=${{ steps.check_version.outputs.version }}
          changed=${{ steps.check_version.outputs.changed }}
          
          echo "Prev version $prev_version"
          echo "Version $version"
          echo "Version has changed $changed"

          if [[ "$version" != "0.37.0" ]]; then
            echo "Invalid 'version'"
            exit 1
          fi
          if [[ $changed != false ]]; then
            echo "Invalid 'changed'"
            exit 1
          fi

      - name: Conditional step
        id: conditional_step
        if: ${{ !steps.check_version.outputs.changed }}
        run: echo "executed=true" >> $GITHUB_OUTPUT

      - name: Test conditional step
        run: |
          if [ ${{ steps.conditional_step.outputs.executed }} != 'true' ]; then
            exit 1
          fi

      - name: Test conditional job
        uses: actions/download-artifact@v4
        with:
          name: 42
