name: Tests
on:
  push:
    branches: [ main ]

jobs:
  check_version:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_version.outputs.changed }}
      version: ${{ steps.check_version.outputs.version }}
      prev_version: ${{ steps.check_version.outputs.prev_version }}
      
    steps:
      - uses: actions/checkout@v4

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

  random:
    name: Generate random
    runs-on: ubuntu-latest
    outputs:
      random: ${{ steps.random.outputs.random }}
    steps:
      - run: echo "random=$RANDOM" >> "$GITHUB_OUTPUT"
  
  conditional_job:
    name: Conditonal job
    needs: [check_version, random]
    if: ${{ needs.check_version.outputs.changed }}
    runs-on: ubuntu-latest

    steps:
      - run: touch ${{ needs.random.outputs.random }}
      
      - name: Upload a file to mark that job executed
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.random.outputs.random }}
          path: ./${{ needs.random.outputs.random }}
            
  test:
    name: Test
    needs: [random]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rm -f ${{ needs.random.outputs.random }}

      - name: Wait for conditional job
        run: sleep 60

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

      - name: Test check_version step
        run: |
          prev_version=${{ steps.check_version.outputs.prev_version }}
          version=${{ steps.check_version.outputs.version }}
          changed=${{ steps.check_version.outputs.changed }}
          
          echo "Prev version $prev_version"
          echo "Version $version"
          echo "Version has changed $changed"

          if [[ "$version" != "0.42.0" ]]; then
            echo "Invalid 'version'"
            exit 1
          fi
          if [[ $changed != false ]]; then
            echo "Invalid 'changed'"
            exit 1
          fi

      - name: Conditional step
        id: conditional_step
        if: ${{ !steps.check_version.outputs.changed }}
        run: echo "executed=true" >> $GITHUB_OUTPUT

      - name: Test conditional step
        run: |
          if [ ${{ steps.conditional_step.outputs.executed }} != 'true' ]; then
            exit 1
          fi

      - name: Test conditional job
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.random.outputs.random }}
