name: Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

      - name: Tests
        run: |
          prev_version=${{ steps.check_version.outputs.prev_version }}
          version=${{ steps.check_version.outputs.version }}
          changed=${{ steps.check_version.outputs.changed }}
          
          echo "Prev version $prev_version"
          echo "Version $version"
          echo "Version has changed $changed"

          if [[ "${ version }" != "0.42.0" ]]; then
            echo "Invalid 'version'"
            exit 1
          fi
          if [[ "${ changed }" != true ]]; then
            echo "Invalid 'changed'"
            exit 1
          fi
