name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_version:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_version.outputs.changed }}
      version: ${{ steps.check_version.outputs.version }}
      prev_version: ${{ steps.check_version.outputs.prev_version }}
      
    steps:
      - uses: actions/checkout@v4

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

  conditional_job:
    name: Conditonal job
    needs: [check_version]
    if: needs.check_version.outputs.changed == 'false'
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "changed = ${{ needs.check_version.outputs.changed }}"
          touch 42
      
      - name: Upload a file to mark that job executed
        uses: actions/upload-artifact@v4
        with:
          name: 42
          path: ./42
            
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for conditional job
        run: sleep 60

      - id: check_version
        uses: radumarias/action-check-version-changed-rust@main

      - name: Test check_version step
        run: |
          prev_version=${{ steps.check_version.outputs.prev_version }}
          version=${{ steps.check_version.outputs.version }}
          changed=${{ steps.check_version.outputs.changed }}
          
          echo "Prev version $prev_version"
          echo "Version $version"
          echo "Version has changed $changed"

          if [[ "$version" != "0.37.0" ]]; then
            echo "Invalid 'version'"
            exit 1
          fi
          if [[ $changed != 'false' ]]; then
            echo "Invalid 'changed'"
            exit 1
          fi

      - name: Conditional step
        id: conditional_step
        if: ${{ !steps.check_version.outputs.changed }}
        run: echo "executed=true" >> $GITHUB_OUTPUT

      - name: Test conditional step
        run: |
          if [ ${{ steps.conditional_step.outputs.executed }} != 'true' ]; then
            exit 1
          fi

      - name: Test conditional job
        uses: actions/download-artifact@v4
        with:
          name: 42
